// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzknEf1rNl1aIvcDaYjogKRJMvmN5db_g',
    appId: '1:315403202807:web:ea1af886c34d634cfbe3f2',
    messagingSenderId: '315403202807',
    projectId: 'quiziknow-7c873',
    authDomain: 'quiziknow-7c873.firebaseapp.com',
    storageBucket: 'quiziknow-7c873.firebasestorage.app',
    measurementId: 'G-JS2JCBNTJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9PHSqg5hs1hXWgMcRFY66A0erN5kMHeQ',
    appId: '1:315403202807:android:5469dad337d0763afbe3f2',
    messagingSenderId: '315403202807',
    projectId: 'quiziknow-7c873',
    storageBucket: 'quiziknow-7c873.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl1zTAA8W0dv4jPCwjTRwr16tDWefe-4s',
    appId: '1:315403202807:ios:2397086d785e4941fbe3f2',
    messagingSenderId: '315403202807',
    projectId: 'quiziknow-7c873',
    storageBucket: 'quiziknow-7c873.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl1zTAA8W0dv4jPCwjTRwr16tDWefe-4s',
    appId: '1:315403202807:ios:2397086d785e4941fbe3f2',
    messagingSenderId: '315403202807',
    projectId: 'quiziknow-7c873',
    storageBucket: 'quiziknow-7c873.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzknEf1rNl1aIvcDaYjogKRJMvmN5db_g',
    appId: '1:315403202807:web:bda345b19aadd9b9fbe3f2',
    messagingSenderId: '315403202807',
    projectId: 'quiziknow-7c873',
    authDomain: 'quiziknow-7c873.firebaseapp.com',
    storageBucket: 'quiziknow-7c873.firebasestorage.app',
    measurementId: 'G-9TZJRC8DCT',
  );
}
